apiVersion: v1
kind: Service
metadata:
  name: gateway-nodeport
  namespace: gateway-ns
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  selector:
    gateway.networking.k8s.io/gateway-name: gateway
    app.kubernetes.io/name: gateway-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31000