apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-cm
data:
  APP: "frontend"
  ENVIRONMENT: "development"
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome</title>
    </head>
    <body>
        <h1>This page is served by nginx. Welcome to Cloud With VarJosh!!</h1>
    </body>
    </html>