apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  ttlSecondsAfterFinished: 60
  completions: 1  # Number of successful runs before job is considered complete
  backoffLimit: 4 # Number of retries before considering job failed
  template:
    spec:
      containers:
        - name: hello
          image: busybox
          command: ["bin/sh", "-c", "echo Hello from the Job! && sleep 10"]
      restartPolicy: Never  # Jobs must use Never or OnFailure. Never creates a new Pod on failure; OnFailure restarts the same Pod.
      